### ISSUE TITLE
How to connect to Azure SQL Database

### ISSUE THREAD

**Issue by survivant** [KarnerTh/mermerd#29]
I'.m trying to connect to a Azure SQL Database, but I'm not able.

````
PS C:\Users\sd003526\Downloads\mermerd_0.5.0_windows_amd64> .\mermerd.exe

.  ..___.__ .  ..___.__ .__
|\/|[__ [__)|\/|[__ [__)|  \
|  |[___|  \|  |[___|  \|__/ (0.5.0)

Create MermaidJs diagrams from your database

? Connection string: [tab for suggestions] sqlserver://user:password@mydatabase.database.window
[========>           ]Connecting to database

X Something went wrong!

PS C:\Users\sd003526\Downloads\mermerd_0.5.0_windows_amd64>
````

I try also with the full ConnectionString given my Azure

``Server=tcp:mydatabase.database.windows.net,1433;Initial Catalog=mydatabase;Persist Security Info=False;User ID=user;Password=password;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;``

and I try with jdbc connection string too ``jdbc:sqlserver://mydatabase.database.windows.net:1433;database=mydatabase;user=user@mydatabase;password=password;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;`` and I got ``X Something went wrong!``

**Comment by adriennn** [comment]
how about this

sqlserver://user:pass@mydb.database.windows.net:1433

**Comment by KarnerTh** [comment]
@survivant as it turns out, Azure SQL can be used with the MSSQL integration (I did not know that the Azure SQL Database is based on the latest stable version of the Microsoft SQL Server database engine).

As @adriennn suggested, using e.g. the connection string `sqlserver://sa:securePassword1!@localhost:1433?database=mermerd_test` works as intended. I added the connection string + an instance of Azure SQL to the integration tests and it works just fine (https://github.com/KarnerTh/mermerd/actions/runs/4127949120/jobs/7131791913) 

If you still have an issue and are sure the connection string works feel free to reopen the issue.
