### ISSUE TITLE
Unable to run under Windows 11 Pro

### ISSUE THREAD

**Issue by mrfatguy** [KarnerTh/mermerd#39]
Greets, is there any specific requirement for this piece of software running it under Windows 11 Pro?

### First issue: Not signed app

App is not signed and forces user to answer dully error message each time it is run interactively:

![mermerd_0 8 0_mermerd_0 8 0_windows_arm64_error_1](https://github.com/KarnerTh/mermerd/assets/2903392/0aaac81f-b11f-4ba2-ba6c-8d1de56165d0)

### Running interactively

When run interactively and the above screen is confirmed (_Run anyway_) it shows a console. Doing _anything_ (except pressing <kbd>Enter</kbd> on empty line):

- typing something that seems to be a valid connection string: `mysql://runs:sTo0qw]HcvWraIPeTs9@localhost:3306/test-rest-api`
- typing a sequence of non-sense characters: `wqdaetgsdhaeheghwehgaeheh`
- typing something stupid: `lazy fox jumped over crazy dog`

quits the app / closes the window.

**Only** Hitting <kbd>Enter</kbd> on empty line does not closes the app and produces following error:

> Sorry, your reply was invalid: Value is required

### Running in command line

Running from Windows Terminal (command line) and typing as above works exactly the same, but before quitting apps shows the following error:

    ? Connection string: mysql://runs:sTo0qw]HcvWraIPeTs9@localhost:3306/test-rest-api
    [                    ]Connecting to database
    
    X Something went wrong!

So something went wrong, but what? Can't it display _any_ readable output or error?

### Running from command line

Following [your guide](https://github.com/KarnerTh/mermerd#example-usages) and trying this:

    mermerd.exe --connectionString mysql://runs:sTo0qw]HcvWraIPeTs9@localhost:3306/test-rest-api

Produces pretty much the same effect:

![mermerd_0 8 0_mermerd_0 8 0_windows_arm64_error_2](https://github.com/KarnerTh/mermerd/assets/2903392/602c7aae-1745-41fe-8a67-c6debaf13d5a)

### Running with configuration file

Again [following your guide](https://github.com/KarnerTh/mermerd#use-a-predefined-run-configuration-eg-for-cicd) using _c.yaml_ configuration file:

    # Connection properties
    connectionString: "mysql://runs:sTo0qw]HcvWraIPeTs9@localhost:3306/test-rest-api"

    # Define what schemas should be used

    useAllSchemas: true

    # Define what tables should be used

    useAllTables: true

    # Additional flags

    showAllConstraints: true
    encloseWithMermaidBackticks: true
    outputFileName: "my-db.mmd"
    debug: true
    showDescriptions:
      - enumValues
      - columnComments
    showSchemaPrefix: true
    schemaPrefixSeparator: "_"

And running it:

    >mermerd --runConfig c.yaml

**Finally** produces some readable error:

    Connecting to databasetime="2023-06-12T08:22:23+02:00" level=error msg="default addr for network 'localhost:3306' unknown"

(I still can't understand why previous methods can't display the same error?)

The problem is that this error seems... wrong. Because both `localhost` is reachable:

![mermerd_0 8 0_mermerd_0 8 0_windows_arm64_error_4](https://github.com/KarnerTh/mermerd/assets/2903392/0f50c567-ba45-46c1-853c-4599de2b0add)

And _mysqld_ is running under port **3306**:

![mermerd_0 8 0_mermerd_0 8 0_windows_arm64_error_5](https://github.com/KarnerTh/mermerd/assets/2903392/343cc029-e786-4394-ad85-8cbf3955826f)

### Conclusion

Can you provide more information on what am I doing wrong or how to use your software under Windows 11? Thank you!

**Comment by KarnerTh** [comment]
Thanks for the detailed issue! 

#### Regarding the "Not signed app"
As far as I understand, I would need to buy a certificate in order to be able to sign the application. Since I don't earn any money with the tool I am not planning to buy a certificate in the near future.
One solution would be to install the tool via `go install github.com/KarnerTh/mermerd@latest` if feasible (you need the go toolchain installed on your local machine - [how to install](https://go.dev/doc/install))

#### Regarding the connection issues
As soon as an error occurs - the program closes. If you start it via command line you see the result in the history, if you start it via the .exe the window will automatically close. I will look into it if that default behaviour can be changed. 

If you use mysql you need to specify the protocol in the connection string, I have an example in the readme [here](https://github.com/KarnerTh/mermerd#connection-strings) 
It looks like `mysql://root:password@tcp(localhost:3306)/yourDb`

If you still have issues you could try to use `127.0.0.1` instead of localhost, sometimes the local DNS is a issue.

Please let me know if the error still exists

**Comment by trejder** [comment]
### Connection issues

Regarding checking, if your program works, I'll need a couple of days to perform some tests. But, given the fact that I was missing the protocol part in my connection string, I assume that it will work just as expected.

But, I need a couple of days to verify this and close this ticket.

### Not signed app

Regarding signing-off your application for Windows 11, it all depends on which tool you are using for building final .exe file from your source code. This is the place, where you should address such question. Because answer will be highly (fundamentally) dependent on that tool.

But, as far I know, it cost 0 USD and all you need to invest into this process is a couple of hours.

This is because this process has nothing to do with payments. And all to do with security. You are signing your application, not to earn money out of it (therefore you don't need no license). But to tell Windows security systems that it is safe for the end user, it comes from a trusted source and by no mean it is a virus, backdoor or otherwise security issue for the end user.

[Here you have](https://onezeronull.com/2015/06/22/deploying-a-phonegap-app-to-windows-marketplace/) my blog post from 2015 (when Windows Phone was still there) on deploying mobile application to Windows Phone system. Completely different situation, but since I was also supporting many platforms (Android, iOS and Windows Phone) out of single source base and since Windows Phone was Windows in fact (only squashed to fit mobile devices) then chances are that you will find some similarities.

Sorry, but this is pretty much all that I can offer you. I have been 8+ years out of coding, so my information is very, very out-dated and probably totally invaluable for you. You need to search the Internet for most recent up-to-date information.

**Comment by aoi-infoport** [comment]
I am also using Windows 11Pro.
When I download the latest memerrd v0.10.0 from the release page and connect to my local mariadb server at the command line, I get the following message.
    
    [ ] Connecting to database
    
    X Something went wrong!
    
On a whim, I tried giving the Windows terminal administrator privileges and was able to get `result.mmd` correctly with the same command.
This may not be safe, but just FYI.

**Running Environment**
Edition: Windows 11 Pro
Version: 23H2
OS build: 22631.2861

**Comment by KarnerTh** [comment]
Sorry but I do not plan to offer a signed version for Windows. If anyone is interested in working on this, I am happy to collaborate.
