### ISSUE TITLE
Special characters in connection uri causing errors

### ISSUE THREAD

**Issue by crdiaz324** [KarnerTh/mermerd#47]
I am trying to connect to a database that has password that begins with a semicolon.  Here are the different approaches that I have tried:

1 - mermerd -c "postgresql://dbuser:;8hi3jj@192.168.111.142:5432/profiles"  # plain password
2 - mermerd -c "postgresql://dbuser:%3B8hi3jj@192.168.111.142:5432/profiles"   # uri encoded the semicolon
3 -  mermerd -c "postgresql://dbuser:${PASSWORD}@192.168.111.142:5432/profiles" # stored the password in an env variable. 

I cannot change the password on this DB, but I would very much like to be able to use this tool.

**Comment by KarnerTh** [comment]
Sorry for the late response, I am quite busy currently.
The Uri encoded password should work - I will look into this as soon as I got the time.

**Comment by hudsonmd** [comment]
This appears to be due to the following change in database/sql which added invalid characters for the connection string

PR: https://go-review.googlesource.com/c/go/+/87038
File: https://go-review.googlesource.com/c/go/+/88535/6/src/net/url/url.go

I was able to work around this by percent encoding any special characters in the connection string and would recommend adding this to the readme. See this link for conversions https://www.w3schools.com/tags/ref_urlencode.ASP
